server:
  port: 8099
spring:
  application:
    name: isc

isc:
  uri: https://218.58.65.133:1443
  url:
    # 获取监控点预览取流URLv2
    preview: /api/video/v2/cameras/previewURLs
    # 查询区域列表v2
    region: /api/irds/v2/region/nodesByParams
    # 根据区域编号获取下级监控点列表
    region_camera: /api/resource/v1/regions/regionIndexCode/cameras
    # 查询监控点列表v2
    page_camera: /api/resource/v2/camera/search
  region:
    code:
      # 五四广场
      wsgc: 37020000001310272140
      # 栈桥
      zq: 37020000001310077955
